[package]
name = "cargo-rbmt"
version = "0.1.0"
authors = ["Nick Johnson <nick@yonson.dev>"]
license = "CC0-1.0"
edition = "2021"
rust-version = "1.74.0"

[[bin]]
name = "cargo-rbmt"
path = "src/main.rs"

[dependencies]
xshell = "0.2.7"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0.179", features = ["derive"] }
serde_json = "1.0.104"
toml = "0.8"
public-api = "0.47"
